### ISSUE TITLE
Encoding consent string functionality

### ISSUE THREAD

**Issue by alexanderedge** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#8]
Hi @chrispaterson,

I'm working on integrating an advertising SDK on iOS which contains the ability to read an IAB consent string from `NSUserDefaults`. However, I see no way to natively create a consent string to save to `NSUserDefaults` in the first instance.

This functionality appears to be omitted from this Swift SDK, but I note that it is present in the [Java SDK](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Java).

Is this likely to be added to the Swift SDK? I notice that there is an [open PR](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Swift/pull/6) which purports to add this functionality, but it hasn't been merged. What would it take to get this merged?

Thanks for your time.

**Comment by chrispaterson** [comment]
Hi @alexanderedge, Initially only the JavaScript SDK had the ability to generate a consent string out the gate.  The thinking initially was that people would just a web view to load a the consent ui which would then would provide the JS API interface to get the consent string from the native layer.

With v2.0 of the TCF we are expanding mobile support a bit to enable native CMP implementations.  I could see Consent String generation being added to the next iteration of the SDK that support TCF 2.0, but since we are beginning the work on that, it's unlikely we would add it to the current SDK that supports v1.1 of the TCF.  The problem with #6 is that it is a massive change and adds features that were not considered through the IAB, like publisher purposes in mobile and a few other things.

**Comment by alexanderedge** [comment]
Thanks for your reply, Chris, that's really helpful. If one was to open a PR with _only_ the support for consent string creation, is it possible that it could be merged?

**Comment by chrispaterson** [comment]
sure, I don't see an issue with that

**Comment by alexanderedge** [comment]
Closing issue since I have opened a PR https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-Swift/pull/9
